### ISSUE TITLE
Mapa en detalle de encuentro

### ISSUE THREAD

**Issue by angardi** [TEDICpy/decidim-reportes#11]
El mapa de ubicacion no se despliega correctamente en la pagina de detalle de un encuentro

[https://beta.encarnacion.org.py/denuncias/i-7/f/51/meetings/2](https://beta.encarnacion.org.py/denuncias/i-7/f/51/meetings/2)

**Comment by diegocrzt** [comment]
Esta es una limitación del servicio de mapas en Encarnación, cuando no encuentra un match entre la direcciónque el usuario escribe y alguna referencia en el servidio de geoposicionamiento, no puede generar un mapa, un workaround es volver a escribir la dirección con algún detalle más que permita al servicio encontrar una referencia.

Sobre este feature no sabemos si su funcionamiento va a ser correcto en nuestro país por que de todos modos no existen suficientes calles barrios y ciudades etiquetadas correctamente en los servicios de mapas, tanto de OSM, como Google maps u otros.
