### ISSUE TITLE
Flujo de creación de reportes tiene muchos pasos que no se usan y es confuso

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/decidim-reportes#14]
Estoy creando un reporte ahora y me pide "Tipo de firma" y me parece que no tiene sentido.

Tampoco tiene sentido ámbito

Por último los textos en la línea de avance (arriba) no parecen tener sentido.

**Comment by diegocrzt** [comment]
En el PR #18, se simplifican los campos y pasos para la creación de reportes.

![20180715193006_m4800](https://user-images.githubusercontent.com/6553005/42739448-91188bde-8865-11e8-89ed-0ad7d4fa8b71.png)
