### ISSUE TITLE
Vista de reportes vacía

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/decidim-reportes#6]
Sale vacía la lista de reportes: 

![seleccion_570](https://user-images.githubusercontent.com/463429/41315751-732ec974-6e5e-11e8-8148-d91496fb2859.png)

A menos que uno marque "Cerradas", ahí sí aparecen.

**Comment by diegocrzt** [comment]
Así mismo, el filtro `Cerradas` muestra los reportes cuya fecha de recogida de firmas es anterior al día de hoy. Este comportamiento también se heredo de iniciativas. En https://github.com/TEDICpy/miciudad2/issues/40 hay un comentario más descriptivo al respecto. 

Este tipo de incidencias tiene relación con https://github.com/TEDICpy/miciudad2/issues/34
Esta fecha de recogida de firmas y la lógica de mostrar u ocultar según esta fecha son necesarias para que el mecanismo de votacíon funcione. Cualquier cambio que queramos hacer al respecto nos lleva a replantearnos qué funcionalidades queremos tener en reportes y como van a funcionar.
