### ISSUE TITLE
Ubicacion de encuentros

### ISSUE THREAD

**Issue by angardi** [TEDICpy/decidim-reportes#7]
No se visualiza el mapa de los encuentros en el frontend. Tambien seria ideal cambiar el motor de mapas por google maps en vez de open street maps

[https://beta.encarnacion.org.py/denuncias/i-7/f/51/meetings/2](https://beta.encarnacion.org.py/denuncias/i-7/f/51/meetings/2)

**Comment by diegocrzt** [comment]
Se corrigió en el repo de miciudad2, había una configuración superpuesta
